# Generated by Django 6.0.3 on 2026-05-07 08:02

from django.db import migrations

def create_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.get_or_create(name="organization_admin")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_group),
    ]
